Update installation.md
blakeblackshear/frigate pull request #10020
Opened 2024-02-24 20:03 UTC by Floriszz

According to the v13 release the config.yml mapping needs to be the entire directory and not only the config.yml file

2024-02-24 21:27 UTC, NickM-27 requested changes
I think we should adjust the existing text and not add on.

2024-02-27 12:53 UTC, blakeblackshear commented on docs/docs/frigate/installation.md
> +- The location of your config file in yaml format, this needs to be file and you need to go to the location of where your config.yml is located, this will be different depending on your NAS folder st
```suggestion
- The location of your config directory which will be different depending on your NAS folder structure e.g. `/docker/frigate/config` will mount to `/config` within the container.
```

2024-02-27 12:53 UTC, blakeblackshear approved these changes

2024-02-27 13:08 UTC, NickM-27 approved these changes

2024-02-27 13:08 UTC, merged