Auth!
blakeblackshear/frigate pull request #11347
Opened 2024-05-12 15:01 UTC by blakeblackshear

2024-05-12 15:20 UTC, NickM-27 commented on web/src/LoginPage.tsx
can we move this to /src/pages ?

2024-05-12 15:20 UTC, NickM-27 commented on web/src/components/AuthForm.tsx
Can we move this to /compnents/auth folder?

2024-05-12 15:37 UTC, NickM-27 commented on frigate/config.py
> +class UserConfig(FrigateBaseModel):
Seems like this may not be used anymore?

2024-05-15 14:21 UTC, NickM-27 commented on web/src/components/menu/AccountSettings.tsx
Maybe we should hide this icon if auth is not enabled?

2024-05-18 16:11 UTC, NickM-27 requested changes

2024-05-18 16:11 UTC, NickM-27 commented on docs/docs/configuration/authentication.md
> +Frigate stores user information in it's database. Password hashes are generated using industry standard PBKDF2-SHA256 with 600,000 iterations. Upon successful login, a JWT token is issued with an exp
```suggestion
Frigate stores user information in its database. Password hashes are generated using industry standard PBKDF2-SHA256 with 600,000 iterations. Upon successful login, a JWT token is issued with an expiration date and set as a cookie. The cookie is refreshed as needed automatically. This JWT token can also be passed in the Authorization header as a bearer token.
```

2024-05-18 16:11 UTC, NickM-27 commented on docs/docs/configuration/authentication.md
> +Users are be managed under at Settings > Authentication.
```suggestion
Users are in the UI managed at Settings > Authentication.
```

2024-05-18 16:28 UTC, NickM-27 approved these changes

2024-05-18 16:36 UTC, merged

2024-08-20 11:09 UTC, wangeris commented
thank you so much for this