Add coco-80 labelmap and update FFmpeg for Rockchip
blakeblackshear/frigate pull request #11695
Opened 2024-06-02 17:31 UTC by MarcA711

- add the coco-80.txt labelmap as discussed in https://github.com/blakeblackshear/frigate/pull/11619
- update FFmpeg for Rockchip to fix color issues reported by @jtut1731 (thank you!) in https://github.com/blakeblackshear/frigate/discussions/11594

2024-06-02 18:03 UTC, NickM-27 approved these changes

2024-06-03 01:36 UTC, blakeblackshear requested changes

2024-06-03 01:36 UTC, blakeblackshear commented on docs/docs/configuration/object_detectors.md
> +The correct labelmap must be loaded for each model. If you use a custom model (see notes below), you must make sure to provide the correct labelmap. The table below lists the correct paths for the bu
```suggestion
The correct labelmap must be loaded for each model. If you use a custom model (see notes below), you must make sure to provide the correct labelmap. The table below lists the correct paths for the bundled models:
```

2024-06-03 01:37 UTC, blakeblackshear approved these changes

2024-06-03 01:47 UTC, merged