feat: add i18n
blakeblackshear/frigate pull request #15678
Opened 2024-12-25 11:53 UTC by ZhaiSoul

## Proposed change

 This PR add web i18n system. 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature
- [x] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code
- [ ] Documentation Update

## Additional information
- This PR is related to issue: 
  #925
  
## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [ ] The code has been formatted using Ruff (`ruff format frigate`)

2024-12-26 14:25 UTC, NickM-27 commented
I'd suggest making sure that all of these objects have translations set https://github.com/blakeblackshear/frigate/blob/00371546a3c394bf1e4806b67e3d489854aa0b94/web/src/utils/iconUtil.tsx#L57

Also, you'll want to rebase your commits on `0.16` branch as this will need to go into that version

2024-12-26 14:29 UTC, ZhaiSoul commented
> I'd suggest making sure that all of these objects have translations set
Of course, I’ll pull the new code right away.

2024-12-26 15:16 UTC, ZhaiSoul commented
The code from the 0.16 branch has been merged.
&nbsp;


宅魂Kill
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nicolas ***@***.***&gt;; 
发送时间: 2024年12月26日(星期四) 晚上10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [blakeblackshear/frigate] feat: add i18n (translation/localization) (PR #15678)














 
I'd suggest making sure that all of these objects have translations set https://github.com/blakeblackshear/frigate/blob/00371546a3c394bf1e4806b67e3d489854aa0b94/web/src/utils/iconUtil.tsx#L57
 
Also, you'll want to rebase your commits on 0.16 branch as this will need to go into that version
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-12-26 15:19 UTC, NickM-27 commented
Sorry, can you rebase on 0.16 (as opposed to merging in), the commits changed when resyncing with dev. 

Let me know if you would like some specific steps on how to do that

2024-12-26 15:25 UTC, ZhaiSoul commented
> Sorry, can you rebase on 0.16 (as opposed to merging in), the commits changed when resyncing with dev.
> 
> Let me know if you would like some specific steps on how to do that

Should I first pull the 0.16 branch, and then use git rebase dev on that branch?

2024-12-26 15:53 UTC, NickM-27 commented
Yeah you can do that

2024-12-26 16:54 UTC, ZhaiSoul commented
> Yeah you can do that

Like this? Sorry. It's my frist open source PR. :(

2024-12-26 16:57 UTC, NickM-27 commented
Yep looks good

2024-12-26 17:22 UTC, NickM-27 commented
Looks like the lint and build is failing

2024-12-26 17:28 UTC, ZhaiSoul commented
> Looks like the lint and build is failing

I fix that. And lint passes

2024-12-26 17:30 UTC, NickM-27 commented
Looks like there are still some issues

2024-12-26 17:48 UTC, ZhaiSoul commented
> Looks like there are still some issues

Fixed!

2024-12-31 08:36 UTC, ZhaiSoul commented
Should we change "Search Setting" to "Explore Setting"?

2025-01-01 14:08 UTC, NickM-27 commented
Yeah I'd suggest getting this up to date with the latest changes in naming

2025-01-01 14:59 UTC, hawkeye217 requested changes

2025-01-01 14:59 UTC, hawkeye217 commented on web/src/components/settings/ZoneEditPane.tsx
> +                {t("object." + item)}
When there is no translation available, the default for `t()` is to print the key passed to it. This is problematic for a few reasons:
- Custom labels won't have a translation
- Any labels already supported by Frigate's models/detectors that are not included in the translation .json file will no longer display the correct label.

There are several cases like this in your PR. When a translation is unavailable, I'd suggest defaulting to the original text in English, not to the key passed to `t()`.

2025-01-01 15:06 UTC, ZhaiSoul commented on web/src/components/settings/ZoneEditPane.tsx
> +                {t("object." + item)}
```t``` function default use English json.
If English json not has key, Maybe we should display origin keyword?
Custom labels don't need translation?

2025-01-01 15:19 UTC, hawkeye217 commented on web/src/components/settings/ZoneEditPane.tsx
> +                {t("object." + item)}
Yes. For example, if `object.customlabel` does not have a translation, currently as your code works, this field shows as `Object.Customlabel`. It should just show as `Customlabel`.

2025-01-02 08:30 UTC, ZhaiSoul commented
> Yeah I'd suggest getting this up to date with the latest changes in naming

But what exactly does "explore" refer to here? Since this word has many meanings when translated into Chinese, I might need more information.

2025-01-02 08:34 UTC, ZhaiSoul commented on web/src/components/settings/ZoneEditPane.tsx
> +                {t("object." + item)}
Add parseMissingKeyHandler.

2025-01-02 14:26 UTC, ZhaiSoul commented
And some text from API.
For example, Export module return some error message.
![QQ20250102-222503](https://github.com/user-attachments/assets/79c5bba1-a24b-499e-8870-03fc9d51131d)
How should we translate messages from the API?

2025-01-02 15:53 UTC, hawkeye217 requested changes

2025-01-02 15:53 UTC, hawkeye217 commented on web/public/locales/en/translation.json
> +    "ui.cameraGroup.add": "添加摄像头组",
```suggestion
    "ui.cameraGroup.add": "Add camera group",
```

2025-02-25 19:41 UTC, closed without merging