Add Alder Lake configuration for hwaccel
blakeblackshear/frigate pull request #3532
Opened 2022-07-25 22:33 UTC by charlesmunger

Fixes #3170

2022-07-25 22:37 UTC, NickM-27 commented
Is this true for 0.10 or are these tested with 0.11? If the RC then this should point towards `release-0.11.0` branch

2022-07-25 23:01 UTC, NickM-27 requested changes

2022-07-25 23:01 UTC, NickM-27 commented on docs/docs/configuration/hardware_acceleration.md
> +### >=10th Generation via Quicksync
I think this should be ####

2022-07-25 23:01 UTC, NickM-27 commented on docs/docs/configuration/hardware_acceleration.md
> +### >=12th Generation via Quicksync
Same here (####)

2022-07-25 23:19 UTC, NickM-27 approved these changes

2022-07-26 04:09 UTC, charlesmunger commented on docs/docs/configuration/hardware_acceleration.md
> +### >=12th Generation via Quicksync
Done

2022-07-26 04:09 UTC, charlesmunger commented on docs/docs/configuration/hardware_acceleration.md
> +### >=10th Generation via Quicksync
Done

2022-07-26 04:09 UTC, charlesmunger commented
> Is this true for 0.10 or are these tested with 0.11? If the RC then this should point towards `release-0.11.0` branch

Done.

2022-08-02 00:58 UTC, charlesmunger commented
So, I think this probably shouldn't be merged as is... or at least more discussion is needed. With a variety of tuning parameters, I've been able to get the camera-to-live-view latency of the QSV decoder down to about 2.5 seconds - and at least for small low framerate video, I did not see any CPU usage improvement vs software decoding. 

With vaapi, I was able to get the same excellent latency as the software decoder, but it _increased_ CPU usage by about half. I suspect that unless hardware accelerated scaling filters are used, hardware acceleration for substreams isn't worthwhile on fast CPUs, because of the cost of copying raw frame data out of GPU memory. And even for people who are downscaling their detect streams, I bet that `lowres 1` or `lowres 2` will probably be quite efficient.

It's easy to imagine a setup where video is decoded in hardware, then motion detection is run via opencv's OpenCL kernels directly, with only frames destined for snapshots or inference going to main memory, but that would be a whole lot more complexity and coupling to hardware, plus you'd likely lose process isolation between ffmpeg and the python process.

2022-08-02 00:58 UTC, closed without merging