FEAT: Support for ffmpeg presets
blakeblackshear/frigate pull request #3840
Opened 2022-09-14 23:01 UTC by NickM-27

Implementation of #3429

I decided to go with a preset for each ffmpeg arg separately as having a separate `preset` field presented a few problems.

1. There would either be a low number of presets and customization (picking and choosing what to support) would be low, or there would be an incredible amount of variations. Per camera there would need to be an option for `specific types of cameras` * `rtsp / other protocols` * `tcp / udp` * `default / with audio`
2. The override behavior would also be difficult to handle, if a user sets `preset` but then also sets other fields as well.

2022-11-29 01:17 UTC, felipecrs commented
Wow. This really looks good. I think you forgot to update this page maybe: https://docs.frigate.video/configuration/index

2022-11-29 01:28 UTC, blakeblackshear requested changes
Just a nitpick. Otherwise looks great.

2022-11-29 01:28 UTC, blakeblackshear commented on frigate/ffmpeg_presets.py
> +    """Return the correct preset if in preset format otherwise return raw input."""
This comment isn't accurate. It returns None if not preset format.

2022-11-29 01:57 UTC, NickM-27 commented
> Wow. This really looks good. I think you forgot to update this page maybe: https://docs.frigate.video/configuration/index

Thank you! I want to leave that page the same, it isn't meant to be copied and it is a good reference for what the default args actually are.

2022-11-29 03:48 UTC, blakeblackshear approved these changes

2022-11-29 03:48 UTC, merged

2022-11-29 13:49 UTC, roger- commented
This looks useful. Will it be possible to define presets in the yaml as well?

2022-11-29 13:53 UTC, felipecrs commented
> This looks useful. Will it be possible to define presets in the yaml as well?

That's a great idea!

2022-11-29 14:12 UTC, NickM-27 commented
> This looks useful. Will it be possible to define presets in the yaml as well? 

Not in this iteration, maybe in the future.

2022-12-04 16:54 UTC, felipecrs commented
I just realized that FFmpeg have built-in support for presets, through files: https://ffmpeg.org/ffmpeg.html#Preset-files

Perhaps we should have taken that route instead. =/

2022-12-04 18:35 UTC, NickM-27 commented
> I just realized that FFmpeg have built-in support for presets, through files: https://ffmpeg.org/ffmpeg.html#Preset-files
> 
> Perhaps we should have taken that route instead. =/
> 

It would be difficult to do the custom fps args for mjpeg and other cases like that

2022-12-04 18:54 UTC, felipecrs commented
That's true. :)