Storage Based Retention
blakeblackshear/frigate pull request #3942
Opened 2022-09-25 17:18 UTC by NickM-27

Currently a proof of concept. Needs more long term testing and there may be some edge cases.

To - Do:

- [ ] Handle case where only retained segments are left and they need to be deleted
- [ ] Potentially enable customization of cleanup and trigger time lengths

2022-09-26 20:25 UTC, NickM-27 commented
I am unsure if when running `reduce_storage_consumption` a camera's current record status (enabled / disabled) should be taken into account. I think my current logic covers that and it shouldn't matter, but curious what others think.

2022-09-26 22:13 UTC, blakeblackshear requested changes
Good first pass. I just think we can get there in a way that's less complex and more efficient.

2022-09-26 22:44 UTC, NickM-27 commented on frigate/storage.py
> +        remaining_storage = round(shutil.disk_usage(RECORD_DIR).free / 1000000, 1)
My unraid setup has a write cache which is where frigate recordings go until the cache gets to a threshold then the recordings are moved to a hard drive until frigate deletes them.

There may be a better way to test this, but I spun all my drives down on Unraid. Frigate recordings were on and being written to the cache drive. I got a shell in frigate and ran this command in python and the sizes were going up over time, but the drive did not spin up. 

I then ran `ls /media/frigate/` and the drive spun up. So we should be good there.

2022-09-26 22:48 UTC, NickM-27 commented on frigate/storage.py
> +            # cameras that are only recording part time
Right, this was mainly due to the fact that I am currently removing recordings from each camera which meant a camera that only recorded occasionally would be required to delete all of its retained segments. With the approach you described above this won't be necessary.

2022-10-09 00:56 UTC, blakeblackshear approved these changes

2022-10-09 00:58 UTC, NickM-27 commented on frigate/storage.py
> +            for recording in recordings.objects().iterator():
The test `def test_storage_cleanup(self):` does capture this so I think it does work this way, but I'll explicitly define it just to be sure

2022-10-09 11:28 UTC, merged

2022-10-28 20:04 UTC, NPutting commented
@NickM-27 Should it be pretty easy to add a config of size to keep free instead of the 1 hour calculation? I think the hour cleanup at a time would still work but having a config for that might be nice as well. Wanted to get your thoughts before I tried to implement it.

2022-10-28 20:23 UTC, NickM-27 commented
> @NickM-27 Should it be pretty easy to add a config of size to keep free instead of the 1 hour calculation? I think the hour cleanup at a time would still work but having a config for that might be nice as well. Wanted to get your thoughts before I tried to implement it. 

It was deliberately left at this for now as our focus for 0.12.0 is stability. In a future release more config options are planned. 

That is to say: feel free to go for it but not sure it'll be included in the upcoming release. That being said, it should be fairly trivial to implement.

2022-10-28 21:24 UTC, NPutting commented
> > @NickM-27 Should it be pretty easy to add a config of size to keep free instead of the 1 hour calculation? I think the hour cleanup at a time would still work but having a config for that might be nice as well. Wanted to get your thoughts before I tried to implement it.
> 
> It was deliberately left at this for now as our focus for 0.12.0 is stability. In a future release more config options are planned.
> 
> That is to say: feel free to go for it but not sure it'll be included in the upcoming release. That being said, it should be fairly trivial to implement.

Awesome, Thanks for the quick reply. It makes sense that this initial feature falls under stability improvements. I'll try and make a draft PR with a configurable limit option and understand if it's pushed off on merging for awhile..

2023-01-02 21:39 UTC, XtremeOwnageDotCom commented
@blakeblackshear 

Make sure to tag/close [#994](https://github.com/blakeblackshear/frigate/issues/994) with this PR.

(I can't touch it. But, this PR resolves that issue)

2023-01-02 21:41 UTC, NickM-27 commented
@XtremeOwnageDotCom I don't think that issue can be closed, there's more configuration and other things that need to be done to fully satisfy that request.

2023-01-02 22:00 UTC, XtremeOwnageDotCom commented
@NickM-27  It meets the requirement for which I originally opened that issue for.

However, I gave up trying to keep up with all of the riff-raff which occurred down in the issue when it went off the rails..