Restructured camera specific documentation
blakeblackshear/frigate pull request #4005
Opened 2022-10-03 21:28 UTC by menkej

* Make room for manufacture specific docs, fixes #3997 
* Added initial (more or less) working setup for Annke C800 camera

2022-10-03 21:47 UTC, NickM-27 requested changes

2022-10-03 21:47 UTC, NickM-27 commented on docs/docs/configuration/camera_specific.md
> +### Unifi Protect Cameras
This should go under the model/vensor specific setup section

2022-10-03 21:47 UTC, NickM-27 commented on docs/docs/configuration/camera_specific.md
> +#### Annke C800
Is there anything specific about the Annke in this case? Seems like these args would be relevant for all H.265 only cameras.

2022-10-03 21:47 UTC, NickM-27 commented on docs/docs/configuration/camera_specific.md
> +      height: 2160 # <---- update for your camera's resolution
```suggestion
    detect:
      width: # <---- update for your camera's resolution
      height: # <---- update for your camera's resolution
```

2022-10-03 21:47 UTC, NickM-27 commented on docs/docs/configuration/camera_specific.md
> +      height: 2160 # <---- update for your camera's resolution
We never recommend running detect on the high res stream.

2022-10-03 21:47 UTC, NickM-27 commented on docs/docs/configuration/camera_specific.md
> +        - person
```suggestion
```

2022-10-03 21:47 UTC, NickM-27 commented on docs/docs/configuration/camera_specific.md
> +        - person
I don't think this is needed as part of the camera specific args.

2022-10-03 21:47 UTC, NickM-27 commented on docs/docs/configuration/camera_specific.md
> +      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
```suggestion
      hwaccel_args: [] # <----- Replace with your hwaccel args
```

2022-10-03 21:47 UTC, NickM-27 commented
As this is just a docs update, you'll probably want to retarget `master` branch with this PR

2022-10-05 17:28 UTC, menkej commented
Why did you change the branch from dev to master @NickM-27 ? dev is default in this repo. How are you using these branches? Just curious - want to get it right next time. ;-)

2022-10-05 17:29 UTC, NickM-27 commented
@menkej `dev` is for new features / work that will be going into a future version of frigate. As these are just docs changes and they are relevant to the current version of frigate, it should target `master` so it will be uploaded to the docs when the PR is merged

2022-10-05 18:17 UTC, NickM-27 approved these changes

2022-10-05 18:18 UTC, NickM-27 commented
Looks good though, thank you!

2022-10-08 02:15 UTC, merged