Add docs about additions
blakeblackshear/frigate pull request #4504
Opened 2022-11-24 18:01 UTC by herostrat

I don't know if this is useful for others and ok for you blake.
Background: I only recently found out about doubletake and thought to make it easier to find useful additions.

If this should not go in the docs, no harm done, you can just close it.

2022-11-24 18:02 UTC, NickM-27 commented
Can you point this at master since it's just a docs update?

I think it would be good to emntion this, `Third Party Integrations` might be a better name but I think it makes sense.

2022-11-24 18:08 UTC, herostrat commented
Sure thing, I will change it to master.

I changed it to "Third Party Extensions" as Integrations is kind of loaded with home-assistant.

2022-11-24 18:13 UTC, NickM-27 commented
> Sure thing, I will change it to master.
> 
> I changed it to "Third Party Extensions" as Integrations is kind of loaded with home-assistant.

Yeah that's fair, sounds good to me

2022-11-24 20:14 UTC, blacknell commented
Couple of spelling mistakes - being not beiung; an overview of additions

2022-11-25 07:00 UTC, blacknell commented
> Couple of spelling mistakes - being not beeing; an overview of additions

@herostrat @NickM-27 - I can't fix these myself as I'm not marked as a repo contributor

2022-11-25 07:12 UTC, herostrat commented
Thanks for the review. I will fix them after work today.

2022-11-25 07:16 UTC, blacknell commented
Could I suggest moving the hyperlink to double take from the heading to the body of text. It's more consistent visually and wasn't immediately obvious.

2022-11-25 11:24 UTC, NickM-27 commented
@blacknell you should be able to make suggestions / comments directly on the code by opening "view files" and then clicking on a line

2022-11-25 12:05 UTC, blacknell requested changes

2022-11-25 12:05 UTC, blacknell commented on docs/docs/integrations/third_party_extensions.md
> +## [Double Take](https://github.com/jakowenko/double-take)
Suggest move the URL from the heading to the paragraph text to be visually consistent with the rest of the documentation (and more obvious)

2022-11-25 12:05 UTC, blacknell commented on docs/docs/integrations/third_party_extensions.md
> +Beeing open source, others have the possibility to modify and extend the rich functionality Frigate already offers.
[spelling] Being

2022-11-25 12:05 UTC, blacknell commented on docs/docs/integrations/third_party_extensions.md
> +This page is meant to be a overview over additions one can make to the home NVR setup. The list is not exhaustive and can be extended via PR to the Frigate docs.
change a to an (an overview)

2022-11-26 14:04 UTC, NickM-27 commented on docs/docs/integrations/third_party_extensions.md
> +:::
```suggestion
:::caution

This page does not recommend or rate the presented projects.
Please use your own knowledge to assess and vet them before you install anything on your system.

:::
```

2022-11-26 14:04 UTC, NickM-27 commented on docs/docs/integrations/third_party_extensions.md
> +[Double Take](https://github.com/jakowenko/double-take) provides an unified UI and API for processing and training images for facial recognition.
Might be worth noting here that doubletake supports automatically setting the sub labels for `Person` objects that are detected and recognized

2023-02-23 19:24 UTC, herostrat commented
Not stale, but I don't know if it is desired

2023-02-23 19:32 UTC, NickM-27 approved these changes

2023-02-24 03:29 UTC, merged

2023-04-02 04:24 UTC, skrashevich commented
This project does not seem to be supported anymore. I have a live [fork](https://github.com/skrashevich/double-take). Maybe it makes sense to replace the link?