docs: adds note about dynamic config
blakeblackshear/frigate pull request #4882
Opened 2023-01-03 22:07 UTC by jritsema

I ran into an issue with this and wanted to help surface up and clarify which sections are supported.

2023-01-03 22:12 UTC, NickM-27 commented on docs/docs/configuration/index.md
> +**Note:**  Dynamic configuration values are currently supported in the following sections: `mqtt.password` and `cameras.<name>.ffmpeg.inputs.[].path`.  Dynamic values can be set using environment var
Definitely a good idea to call out, but I don't think there is a reason to be as technical. Can just say it is only supported for MQTT Password and ffmpeg paths

2023-01-03 22:22 UTC, NickM-27 approved these changes

2023-01-04 01:28 UTC, blakeblackshear requested changes
I don't like the term "Dynamic configuration values". I would just state that "Environment variable substitution is only supported..." and "Only environment variables starting with FRIGATE_ will be used".

2023-01-20 19:27 UTC, felipecrs commented on docs/docs/configuration/index.md
> +**Note:**  Dynamic configuration values are currently only supported for MQTT password and camera ffmpeg paths.  Dynamic values can be set using environment variables with names starting with `FRIGAT
```suggestion
**Note:**  Dynamic configuration values are currently only supported for MQTT password and camera ffmpeg paths. Dynamic values can be set using environment variables with names starting with `FRIGATE_`.  For example, `{FRIGATE_MQTT_PASSWORD}`, `{FRIGATE_RTSP_USER}`, `{FRIGATE_RTSP_PASSWORD}`.
```

2023-02-20 03:03 UTC, jritsema commented
Last commit addresses @blakeblackshear's [comment](https://github.com/blakeblackshear/frigate/pull/4882#pullrequestreview-1235268572).

2023-03-07 12:28 UTC, blakeblackshear approved these changes

2023-03-07 12:28 UTC, merged