Add Save Only button to config editor
blakeblackshear/frigate pull request #5090
Opened 2023-01-14 19:11 UTC by yeahme49

Gives an option to only save the config, not save and restart, when using the config editor.  Requested here: https://github.com/blakeblackshear/frigate/discussions/5082

2023-01-14 19:16 UTC, NickM-27 approved these changes

2023-01-14 22:41 UTC, NickM-27 commented
Need to fix python linter

2023-01-15 04:42 UTC, yeahme49 commented
Should be fixed now

2023-01-15 15:37 UTC, blakeblackshear requested changes
I think this should be done as a query string parameter rather than a header.

2023-01-15 17:00 UTC, NickM-27 approved these changes

2023-01-15 17:25 UTC, blakeblackshear approved these changes

2023-01-15 17:25 UTC, merged