Try to limit nvidia GPU queries to included GPUs
blakeblackshear/frigate pull request #5356
Opened 2023-02-02 19:04 UTC by jvrobert

Not sure this is the best solution, but it's a solution for now, pretty niche case probably anyway.

2023-02-02 19:36 UTC, NickM-27 requested changes

2023-02-02 19:36 UTC, NickM-27 commented on frigate/util.py
> +    if ("CUDA_VISIBLE_DEVICES" in os.environ):
You're going to need to handle the case where the value for this env variable is `ALL` in which case we should not append an --id (same for the other env check as well)

2023-02-02 19:37 UTC, NickM-27 commented on frigate/util.py
> +    if ("CUDA_VISIBLE_DEVICES" in os.environ):
Probably just only append it if it's an int

2023-02-02 21:08 UTC, NickM-27 commented
you need to fix the python checks by running `python3 -m black frigate`

2023-02-03 13:47 UTC, NickM-27 requested changes

2023-02-03 13:47 UTC, NickM-27 commented on frigate/util.py
> +
```suggestion
    if (
        "CUDA_VISIBLE_DEVICES" in os.environ 
        and os.environ["CUDA_VISIBLE_DEVICES"].isdigit()
    ):
        nvidia_smi_command.extend(["--id", os.environ['CUDA_VISIBLE_DEVICES']])
    elif (
        "NVIDIA_VISIBLE_DEVICES" in os.environ 
        and os.environ["NVIDIA_VISIBLE_DEVICES"].isdigit()
    ):
        nvidia_smi_command.extend(["--id", os.environ['NVIDIA_VISIBLE_DEVICES']])

```

2023-02-03 13:50 UTC, NickM-27 requested changes

2023-02-03 13:50 UTC, NickM-27 commented on frigate/util.py
> +        nvidia_smi_command.extend(["--id", os.environ['NVIDIA_VISIBLE_DEVICES']])
```suggestion
    if (
        "CUDA_VISIBLE_DEVICES" in os.environ
        and os.environ["CUDA_VISIBLE_DEVICES"].isdigit()
    ):
        nvidia_smi_command.extend(["--id", os.environ["CUDA_VISIBLE_DEVICES"]])
    elif (
        "NVIDIA_VISIBLE_DEVICES" in os.environ
        and os.environ["NVIDIA_VISIBLE_DEVICES"].isdigit()
    ):
        nvidia_smi_command.extend(["--id", os.environ["NVIDIA_VISIBLE_DEVICES"]])
```

2023-02-03 13:50 UTC, NickM-27 approved these changes

2023-02-04 01:34 UTC, blakeblackshear approved these changes

2023-02-04 01:34 UTC, merged