Events Page: Added option to override browser time format and style
blakeblackshear/frigate pull request #5538
Opened 2023-02-18 17:33 UTC by sinamics

Implements #5476

new optional ui config entries:
```yaml
ui:
  use12hour: false     # true | false
  dateStyle: 'short'   # 'full' | 'long' | 'medium' | 'short
  timeStyle: 'medium'  # 'full' | 'long' | 'medium' | 'short
```

Would be nice if someone else could test and provide feedback.
one issue, when "full" is used (highly unlikely) it will clutter the mobile view, but at least it gives the user the option.

A few examples:

```
ui:
  dateStyle: 'full' 
  timeStyle: 'full'
```
![image](https://user-images.githubusercontent.com/7771916/219879747-b7922af9-45bc-474a-b85d-28376235a49a.png)

```
(default)
ui:
  dateStyle: 'short' 
  timeStyle: 'medium'
```
![image](https://user-images.githubusercontent.com/7771916/219879625-7671dd0a-43c0-48c5-bdcb-12276d984938.png)

```
ui:
  use12hour: true
  dateStyle: 'short' 
  timeStyle: 'medium'
```
![image](https://user-images.githubusercontent.com/7771916/219879666-32bf5881-123b-452f-81d5-80396e17c50e.png)

```
ui:
  use12hour: true
  dateStyle: 'short' 
  timeStyle: 'short'
```
![image](https://user-images.githubusercontent.com/7771916/219879931-ab5c8432-1e45-4560-b895-f1ad892c0d96.png)

2023-02-18 17:35 UTC, NickM-27 commented
Are the date separators still inherited from the language?

2023-02-18 18:50 UTC, sinamics commented
> Are the date separators still inherited from the language?

damn, your are fast.  :+1:
I tested using 'en-US' instead of 'nb-NO' as language and it changes the date format from to M/d/yyyy.
tested on Edge, Chrome, Firefox

2023-02-18 19:02 UTC, NickM-27 approved these changes

2023-02-18 19:36 UTC, ehn commented
I think this only captures a few of the date/time formats people want. For example, if you're outside of the US you probably don't want M/d/yyyy even if you want your UI in English. This won't let you set your date/time formats independent of the language.

How about letting the user specify an explicit [strftime()](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior) format string? Alternatively, specifying another POSIX locale for LC_TIME?

2023-02-19 09:27 UTC, sinamics commented
Take 2
Modified based on @ehn comment. I do see the usecase to explicit define the date format in some cases and strftime would satisfy all users due to the flexibillity.

I was indecisive about whether to keep the previous configuration or switch entierly to strftime. After evaluating the added complexity that comes with using strftime, I decided to keep both solutions for the time being. Some users may only want to utilize use12hour.

config:
```yaml
ui:
  use12hour: false # true | false
  dateStyle: 'short' # 'full' | 'long' | 'medium' | 'short
  timeStyle: 'medium' # 'full' | 'long' | 'medium' | 'short
  # NOTE! If strftime_fmt are provided it will takes precedence over the others
  strftime_fmt: '%A, %B %e, %Y %I:%M:%S %p %Z'
```

couple of thoughts
- In order to provide more local-specific formatting, strftime supports a few [locales](https://github.com/samsonjs/strftime#bundled-locales). The locale for the user's browser will be used if e.g full time pattern format is specified with the day in clear text.
- To support the use of strftime in the frontend, the strftime (MIT) npm package has been included in the project.
- If strftime_fmt are provided it will takes precedence over the others
- strftime_fmt config entry has no validation for now, so if users type in "hello world" it will be shown in the datetime field. I find it tricky to generate a reqex to validate the string as there is so many diffrent variation of the strftime format.

frontend
```ts
    // use strftime_fmt if defined in config file
    if (strftime_fmt) {
      const strftime_locale = strftime.localizeByIdentifier(locale);
      return strftime_locale(strftime_fmt, date);
    }

    // else use Intl.DateTimeFormat
    const formatter = new Intl.DateTimeFormat(locale, {
      dateStyle,
      timeStyle,
      timeZone: timezone || Intl.DateTimeFormat().resolvedOptions().timeZone,
      hour12: use12hour !== null ? use12hour : undefined,
    });
    return formatter.format(date);
```

2023-02-19 13:21 UTC, NickM-27 requested changes

2023-02-19 13:21 UTC, NickM-27 commented on frigate/config.py
> +        None, title="Override date and time format using strftime syntax."
Maybe add default= just to match other lines

2023-02-19 13:21 UTC, NickM-27 commented on frigate/config.py
> +    timeStyle: DateTimeStyleEnum = Field(
```suggestion
    time_style: DateTimeStyleEnum = Field(
```

2023-02-19 13:21 UTC, NickM-27 commented on frigate/config.py
> +    dateStyle: DateTimeStyleEnum = Field(
```suggestion
    date_style: DateTimeStyleEnum = Field(
```

2023-02-19 13:44 UTC, blakeblackshear commented
We don't use camelCase for any other properties in the config. Lets switch these to underscores for consistency.

2023-02-19 14:23 UTC, NickM-27 approved these changes

2023-02-20 23:17 UTC, NickM-27 requested changes
This option needs to be added to the docs. I would also suggest linking to https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html so users are aware how it works

2023-02-20 23:18 UTC, NickM-27 commented
Have to say though, I wasn't super interested in this until I started playing with it but it is really nice being able to fully customize how the dates / times are presented

2023-02-22 07:09 UTC, sinamics commented
i will be away for the next week, but will update the docs when im back.

2023-02-22 13:53 UTC, blakeblackshear approved these changes

2023-02-22 13:54 UTC, NickM-27 approved these changes

2023-02-22 13:54 UTC, merged

2023-03-14 07:48 UTC, ehn commented
There seems to be a bug here. If you set `strftime_fmt` (in my case to `"%Y-%m-%d %H:%M:%S"`), the presentation ignores the `timezone` setting (in my case `Europe/Stockholm`).

Please let me know if it's better to open a new issue than discuss it here.

2023-11-26 10:32 UTC, brunopiras commented
> There seems to be a bug here. If you set `strftime_fmt` (in my case to `"%Y-%m-%d %H:%M:%S"`), the presentation ignores the `timezone` setting (in my case `Europe/Stockholm`).
> 
> Please let me know if it's better to open a new issue than discuss it here.

Me too, without strftime_fmt the time is set to timezone!