Improve documentation on web rtc
blakeblackshear/frigate pull request #6005
Opened 2023-04-12 02:41 UTC by Juliafin

This improves some documentation on getting web rtc working, especially when running frigate on different host machine. Please let me know if you have any further improvements or suggestions.

2023-04-13 22:38 UTC, NickM-27 requested changes

2023-04-14 00:48 UTC, Juliafin commented on docs/docs/configuration/live.md
> +      - "8555:8555"
Great suggestions! Thank you for reviewing.

2023-04-14 01:09 UTC, NickM-27 commented on docs/docs/configuration/live.md
> +      - "8555:8555"
Sorry, what I meant was you should take the way it is shown there (where it maps tcp and udp) and apply that to your changes in live.md

2023-04-14 01:14 UTC, NickM-27 submitted a review, later dismissed

2023-04-14 14:02 UTC, NickM-27 approved these changes

2023-04-14 14:02 UTC, merged