[Docs] Snapshot config explanation.
blakeblackshear/frigate pull request #6439
Opened 2023-05-08 13:05 UTC by Nornode

related to: https://github.com/blakeblackshear/frigate/issues/6434

2023-05-08 13:08 UTC, NickM-27 requested changes

2023-05-08 13:08 UTC, NickM-27 commented on docs/docs/configuration/snapshots.md
> +Camera specific snapshot can be configured in `config.yml` under  `cameras -> camera -> mqtt` over at [config file](https://docs.frigate.video/configuration/)
```suggestion
Object specific snapshots for each camera can be configured in the [config file](https://docs.frigate.video/configuration/) under  `cameras -> your_camera -> mqtt`
```

2023-05-08 13:08 UTC, NickM-27 commented on docs/docs/configuration/snapshots.md
> +Camera specific snapshot can be configured in `config.yml` under  `cameras -> camera -> mqtt` over at [config file](https://docs.frigate.video/configuration/)
Not all config files are named the same, also want to be clear it is not the same snapshot that is referenced above in that file

2023-05-08 13:17 UTC, NickM-27 submitted a review, later dismissed

2023-05-17 12:45 UTC, blakeblackshear approved these changes

2023-05-17 12:45 UTC, merged