add ffmpeg bandwidth stats
blakeblackshear/frigate pull request #6492
Opened 2023-05-15 00:49 UTC by jarzebski

Added ffmpeg stream bandwidth stats via nethogs

![image](https://github.com/blakeblackshear/frigate/assets/3647/21341a89-6d60-4f42-9cf9-9d3c5784aa8d)

2023-05-15 02:07 UTC, NickM-27 requested changes

2023-05-15 02:07 UTC, NickM-27 commented on web/src/routes/System.jsx
> +                          <Th>Bandwidth KB/s</Th>
```suggestion
                          <Th>Network Bandwidth</Th>
```

2023-05-15 02:07 UTC, NickM-27 commented on web/src/routes/System.jsx
> +                          <Th>Bandwidth KB/s</Th>
I think this makes it more clear the type of bandwidth, and the unit is shown for each row already

2023-05-15 13:00 UTC, NickM-27 approved these changes

2023-05-18 00:09 UTC, jarzebski commented
i'm fix black formatting :) sorry

2023-05-18 00:11 UTC, NickM-27 approved these changes

2023-05-18 01:01 UTC, merged