Nethog option
blakeblackshear/frigate pull request #6615
Opened 2023-05-25 21:36 UTC by NickM-27

Closes #6613

2023-05-26 01:31 UTC, skrashevich commented
it's overkill for resolve #6613 :)

2023-05-26 02:05 UTC, NickM-27 commented
Maybe, but I agree that many users (like myself) won't have use for these and there's no sense taking up extra time for stats which aren't needed, especially as more and more types of stats are added.

2023-05-26 10:02 UTC, blakeblackshear commented
Perhaps we should expand this scope to allow disabling all stats that require spawning external processes. The system page used to be very fast. For example, gpu usage never really changes once things are up and running.

2023-05-26 10:44 UTC, skrashevich commented
Absolutely agree. I was precisely endeavoring to minimize the invocation of external processes during the statistics calculations (#6298, #6344, #6359).

2023-06-11 12:32 UTC, blakeblackshear requested changes

2023-06-11 12:32 UTC, blakeblackshear commented on docs/docs/configuration/index.md
> +    amd_gpu_stats: true
```suggestion
    amd_gpu_stats: True
```

2023-06-11 12:32 UTC, blakeblackshear commented on docs/docs/configuration/index.md
> +    intel_gpu_stats: true
```suggestion
    intel_gpu_stats: True
```

2023-06-11 13:02 UTC, blakeblackshear approved these changes

2023-06-11 13:26 UTC, merged