Ability to configure min frames for zone presence
blakeblackshear/frigate pull request #6680
Opened 2023-06-01 17:19 UTC by NickM-27

I made this work as a zone inertia where the object needs to be detected in the zone in quick succession to be considered in the zone.

2023-06-11 12:30 UTC, blakeblackshear requested changes

2023-06-11 12:30 UTC, blakeblackshear commented on frigate/config.py
> +        title="Number of frames required for object to be considered present in the zone.",
```suggestion
        title="Number of consecutive frames required for object to be considered present in the zone.",
```

2023-06-11 12:30 UTC, blakeblackshear commented on docs/docs/configuration/index.md
> +        # Optional: Set the inertia required for an object to be considered present in the zone. Allowed values are 0 < inertia < 10 (default: shown below)
```suggestion
        # Optional: Number of consecutive frames required for object to be considered present in the zone. Allowed values are 1-10 (default: shown below)
```

2023-06-11 13:00 UTC, blakeblackshear approved these changes

2023-06-11 13:00 UTC, merged

2023-07-10 08:32 UTC, Inrego commented
Any idea when this will be merged into latest? I don't know much about the release cycle of Frigate.

2023-07-10 11:47 UTC, Inrego commented
Is there a roadmap or similar where I can see what's planned for 0.13 to get an idea of the progress towards that goal?

2023-07-10 12:02 UTC, NickM-27 commented
https://github.com/blakeblackshear/frigate/pull/6262