UI Improvement: Full-width birdseye (if no PTZ cameras)
blakeblackshear/frigate pull request #6817
Opened 2023-06-15 14:16 UTC by skrashevich

I don't see any reason why needs limit the size of the Birdseye player window

2023-06-15 14:20 UTC, skrashevich commented
> Because there is already a full screen option and opening the screen to have the full screen taken up is a jarring user experience

By default, Birdseye size is 1280x720. Player will not be larger than it.
In your opinion, 1280x720 is a resolution that can occupy the entire screen in 2023 and cause irritation?

2023-06-15 14:46 UTC, skrashevich commented
> Also, that is incorrect for the JSMpegPlayer, the JSMpegPlayer takes up the entire screen regardless of the resolution birdseye is set to

That's not now
[ea31166](https://github.com/blakeblackshear/frigate/pull/6817/commits/ea311661d7d9dbe3c2afe61f03f9c4c1cceffa60)

2023-06-15 15:05 UTC, NickM-27 commented
The correct solution may be to implement the ability to use the mouse to drag the edge of the birdseye window to make it larger / smaller and to remember that value. 

Otherwise it only works for one usecase or the other

2023-06-15 18:24 UTC, NickM-27 commented
or a separate button similar to how YouTube has a small and large player options

2023-06-15 18:26 UTC, skrashevich commented
> or a separate button similar to how YouTube has a small and large player options

Good idea

2023-06-17 13:26 UTC, NickM-27 requested changes

2023-06-17 13:26 UTC, NickM-27 commented on web/src/routes/Birdseye.jsx
> +            onChange={(e) => setIsMaxWidth(e.target.value)}
This seems like it should not have changed, now there is no way to set the source of the live view?

2023-06-19 19:04 UTC, skrashevich commented
![frigate-birdseye](https://github.com/blakeblackshear/frigate/assets/15078499/bd5dbf10-c824-4536-bcc3-2a2c934fa975)

2023-06-19 19:06 UTC, NickM-27 requested changes
Looks good! I think these comments can be removed

2023-06-19 19:29 UTC, NickM-27 approved these changes

2023-06-19 19:58 UTC, skrashevich commented
More pretty
<img width="1666" alt="image" src="https://github.com/blakeblackshear/frigate/assets/15078499/18c448be-6c36-4f7b-9191-49c9cc5f3192">

2023-06-19 21:02 UTC, NickM-27 approved these changes

2023-07-07 12:09 UTC, merged