configurable ffmpeg timeout
blakeblackshear/frigate pull request #6897
Opened 2023-06-23 15:04 UTC by spacebares

With the default hard-coded 10 seconds, there is a chance to lose a whole 10 seconds of footage when a **battery camera** activates.
If you configure the timeout to 1 second, now the maximum amount of footage lost is 1 second of footage.

This can increase the rate of which ffmpeg processes spawn by 10x but in my testing none of these processes linger even after months of operation and consume almost no cpu when spawned.

Obviously not the best solution, but hardcoding 10 seconds isnt either 😉

2023-06-23 15:09 UTC, NickM-27 requested changes

2023-06-23 15:09 UTC, NickM-27 commented on frigate/config.py
> +    timeout: float = Field(
I don't think timeout is a good name as it's confused with the actual meaning of timeout (how long of no communication should result in an error).

I think `healthcheck_interval` might be better

2023-06-23 15:09 UTC, NickM-27 commented on frigate/video.py
> +        sleeptime = self.config.ffmpeg.timeout
There's no reason to read from the config every time, should be set as self.healthcheck_interval in init and then read here.

2023-06-23 18:04 UTC, NickM-27 approved these changes

2023-06-24 01:32 UTC, blakeblackshear commented
I actually think `retry_interval` or `reconnect_interval` is a more appropriate name. Healthcheck implies a check against a running service.

2023-06-24 12:27 UTC, spacebares commented
maybe `errorcheck_interval` or `errorscan_interval` ?

2023-06-24 17:10 UTC, NickM-27 commented
Right, I think for the functionality retry_interval makes sense to me

2023-06-28 10:48 UTC, blakeblackshear commented on frigate/config.py
> +        default=10.0, title="Time in seconds in-between FFmpeg health checks."
```suggestion
        default=10.0, title="Time in seconds to wait before FFmpeg retries connecting to the camera."
```

2023-06-28 10:49 UTC, blakeblackshear commented
This looks good. It just needs to be added to the configuration reference in the docs.

2023-06-28 19:57 UTC, NickM-27 approved these changes

2023-06-28 19:58 UTC, NickM-27 commented
oops looks like black needs to be run

2023-06-30 12:14 UTC, merged