docs for onvif camera support
blakeblackshear/frigate pull request #7999
Opened 2023-09-29 18:09 UTC by hawkeye217

2023-09-29 18:18 UTC, NickM-27 requested changes

2023-09-29 18:18 UTC, NickM-27 commented on docs/docs/configuration/cameras.md
> +## ONVIF PTZ camera recommendations
Let's change from working / partially working to something like `basic` and `advanced` or something. amcrest for all intents and purposes works just some models don't support the advanced features like autotracking

2023-09-29 18:18 UTC, NickM-27 commented on docs/docs/configuration/cameras.md
> +| Vikylin PTZ-2804X-I2     | Not working       | Incomplete ONVIF support                                              |
I think we should alphabetize this list

2023-09-29 18:39 UTC, NickM-27 approved these changes

2023-09-29 22:52 UTC, merged

2024-04-21 15:20 UTC, shaunpatterson1983 commented
Seems fixed on C210 for Tapo with latest firmware

![image](https://github.com/blakeblackshear/frigate/assets/31116172/23c37982-d9b6-4c10-8932-8025d6904be9)

live:
      stream_name: Study_Sub
    onvif:
      host: 192.168.0.200
      port: 2020