Update restream.md
blakeblackshear/frigate pull request #8015
Opened 2023-10-01 20:17 UTC by lpdescamps

show the code for streaming birdseye

2023-10-01 20:21 UTC, NickM-27 requested changes

2023-10-01 20:21 UTC, NickM-27 commented on docs/docs/configuration/restream.md
> +  mode: continuous
This isn't required for restream so best to not include

2023-10-01 20:21 UTC, NickM-27 commented on docs/docs/configuration/restream.md
>  Birdseye RTSP restream can be enabled at `birdseye -> restream` and accessed at `rtsp://<frigate_host>:8554/birdseye`. Enabling the restream will cause birdseye to run 24/7 which may increase CPU usa
```suggestion
 Birdseye RTSP restream can be accessed at `rtsp://<frigate_host>:8554/birdseye`. Enabling the restream will cause birdseye to run 24/7 which may increase CPU usage somewhat.

```

2023-10-02 12:09 UTC, NickM-27 commented on docs/docs/configuration/restream.md
> +  mode: continuous
```suggestion
```

2023-10-02 12:13 UTC, NickM-27 approved these changes

2023-10-16 02:12 UTC, NickM-27 commented
@blakeblackshear looks like the tests for master are failing for some reason, guess something is out of date. not sure if it makes sense to merge as is anyway knowing that this is fixed in dev or if these PRs should be updated to target dev

2023-10-16 02:14 UTC, blakeblackshear commented
I would just update the PR to dev

2023-11-19 00:10 UTC, closed without merging