Add endpoint to restart Frigate
blakeblackshear/frigate pull request #8440
Opened 2023-11-03 03:14 UTC by coperni

This PR:

- Adds a new endpoint `/api/restart` to restarts Frigate.

The only means of restarting Frigate remotely is to issue a restart topic on the server's websocket. It's
convenient to also expose this capability via HTTP endpoint. I'm a Home Assistant user and use Frigate frequently to recast my RTSP feeds. I find that I have to restart occasionally to get the feeds back up. Adding this capability would help me automate restarting Frigate. 

Open to any suggestions for a way to restart Frigate restfully if there is a better path.

2023-11-03 08:21 UTC, tpjanssen commented
Isn't it better to add some magic key in the body of the request? I foresee a lot of browsers reloading this page, resulting in unwanted restarts.

2023-11-03 10:35 UTC, blakeblackshear approved these changes

2023-11-03 11:07 UTC, blakeblackshear requested changes
This will need to be added to the api page in the docs

2023-11-03 12:35 UTC, NickM-27 requested changes

2023-11-03 12:35 UTC, NickM-27 commented on docs/docs/integrations/api.md
> +Restarts Frigate process.
```suggestion

### `POST /api/restart`

Restarts Frigate process.
```

2023-11-03 16:50 UTC, NickM-27 approved these changes

2023-11-04 02:19 UTC, blakeblackshear approved these changes

2023-11-04 02:19 UTC, merged