Included caution about Snapcraft docker issues.
blakeblackshear/frigate pull request #8925
Opened 2023-12-11 15:09 UTC by FinnakaLite

I have created a caution about the use of Snapcraft docker and how it affects storage locations. 

If you use the Snapcraft build of Docker, you cannot use storage locations outside of your $HOME directory. This is something that I struggled with for months before figuring it out. (Refer to issue #8592)

2023-12-11 15:12 UTC, NickM-27 requested changes

2023-12-11 15:12 UTC, NickM-27 commented on docs/docs/frigate/installation.md
> +:::caution
```suggestion

:::caution
```

2023-12-11 17:15 UTC, NickM-27 approved these changes

2023-12-12 10:48 UTC, blakeblackshear approved these changes

2023-12-12 10:48 UTC, merged