Add ability to customize order of output for edge tpu detector models
blakeblackshear/frigate pull request #9455
Opened 2024-01-26 20:34 UTC by alec-groff

Add order to config.model to allow the user the ability to specify the order of boxes, scores, class_ids, and count for their edge tpu detector output. The default value is the current setting.

2024-01-26 20:37 UTC, NickM-27 requested changes

2024-01-26 20:37 UTC, NickM-27 commented on frigate/detectors/plugins/edgetpu_tfl.py
> +            self.order = detector_config.model.order
I don't think there is a reason to set `self.order` every time, just set it once in init

2024-01-26 20:37 UTC, NickM-27 commented on frigate/detectors/detector_config.py
> +    order: list[int] = Field(
this config would apply to every detector so it needs to be used for every detector or perhaps the default value should be `None` and the field changes to be called `custom_model_output_order` or something

2024-01-26 20:37 UTC, NickM-27 commented on frigate/detectors/detector_config.py
> +    order: list[int] = Field(
I think the name should be more descriptive like `model_output_tensor_order` or something

2024-02-09 21:10 UTC, bazylhorsey commented
Any update on this?

2024-08-01 16:49 UTC, closed without merging