Docs: Fix and clarify which /dev/video devices to use with Raspberry Pi
blakeblackshear/frigate pull request #9509
Opened 2024-01-31 05:49 UTC by m-d-brown

2024-02-07 07:49 UTC, m-d-brown commented
Commenting again in case this got lost in the queue.

2024-02-07 13:02 UTC, NickM-27 requested changes

2024-02-07 13:02 UTC, NickM-27 commented on docs/docs/configuration/hardware_acceleration.md
> +addon, you may need to turn off `Protection mode` for hardware acceleration.
```suggestion
Ensure you increase the allocated RAM for your GPU to at least 128 (`raspi-config` > Performance Options > GPU Memory).  
If you are using the HA addon, you may need to use the full access variant and turn off `Protection mode` for hardware acceleration.
```

2024-02-07 13:02 UTC, NickM-27 commented on docs/docs/configuration/hardware_acceleration.md
> +Use one of these settings in your `frigate.yaml`:
```suggestion
```

2024-02-08 13:26 UTC, NickM-27 approved these changes, later dismissed

2024-02-10 19:44 UTC, blakeblackshear approved these changes

2024-02-10 19:44 UTC, merged